# Lista de constantes utilizadas
INVALIDO = 'INVÁLIDO'
ARTIGO = 'ARTIGO'
ADJETIVO = 'ADJETIVO'
SUBSTANTIVO = 'SUBSTANTIVO'
NUMERAL = 'NUMERAL'
PRONOME = 'PRONOME'
ADVERBIO = 'ADVÉRBIO'
CONJUNCAO = 'CONJUNÇÃO'
PREPOSICAO = 'PREPOSIÇÃO'
INTERJEICAO = 'INTERJEIÇÃO'
VERBO = 'VERBO'
VERBO_AUX = 'VERBO AUXILIAR'
PARTICIPIO = 'PARTICÍPIO'
PALAVRA_DEN = 'PALAVRA DENOTATIVA'
MOEDA = 'SÍMBOLO DA MOEDA CORRENTE'
NLTK = 'NLTK'
SPACY = 'spaCy'

# Mensagens de erro
ERRO_ATOR_INCONSISTENTE = 'Erro de inconsistência no template de validação do ator da história de usuário.'
ERRO_ACAO_INCONSISTENTE = 'Erro de inconsistência no template de validação da ação da história de usuário.'
ERRO_FINALIDADE_INCONSISTENTE = 'Erro de inconsistência no template de validação da finalidade da história de usuário.'