# Lista de constantes utilizadas
INVALIDO = 'INVÁLIDO'
ARTIGO = 'ARTIGO'
ADJETIVO = 'ADJETIVO'
SUBSTANTIVO = 'SUBSTANTIVO'
NUMERAL = 'NUMERAL'
PRONOME = 'PRONOME'
ADVERBIO = 'ADVÉRBIO'
CONJUNCAO = 'CONJUNÇÃO'
PREPOSICAO = 'PREPOSIÇÃO'
INTERJEICAO = 'INTERJEIÇÃO'
VERBO = 'VERBO'
VERBO_AUX = 'VERBO AUXILIAR'
PARTICIPIO = 'PARTICÍPIO'
PALAVRA_DEN = 'PALAVRA DENOTATIVA'
MOEDA = 'SÍMBOLO DA MOEDA CORRENTE'
NLTK = 'NLTK'
SPACY = 'spaCy'
DADO = 'Dado'
GIVEN = 'Given'
QUANDO = 'quando'
WHEN = 'when'
ENTAO = 'então'
THEN = 'then'

# Constantes spaCy
SPACY_EN = 'en_core_web_sm'
SPACY_PT = 'pt_core_news_sm'

# Idiomas
EN = 'en'
PTBR = 'ptbr'

# Mensagens de erro
ERRO_ATOR_INCONSISTENTE = 'Erro de inconsistência no template de validação do ator da história de usuário.'
ERRO_ACAO_INCONSISTENTE = 'Erro de inconsistência no template de validação da ação da história de usuário.'
ERRO_FINALIDADE_INCONSISTENTE = 'Erro de inconsistência no template de validação da finalidade da história de usuário.'
ERRO_FINALIDADE_INCONSISTENTE_2 = 'Erro de inconsistência no template de validação da finalidade dentro do cenário.'
ERRO_ATOR_INCONSISTENTE_2 = 'Erro de inconsistência no template de validação do ator dentro do cenário.'
ERRO_ACAO_INCONSISTENTE_2 = 'Erro de inconsistência no template de validação da ação dentro do cenário.'
ERRO_ACAO_INCONSISTENTE_3 = 'Erro de inconsistência no template de validação da ação dentro do cenário. Um ou mais atores e/ou ações identificadas.'